version: "3.8"
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy 
    container_name: nginx-proxy
    restart: always
    ports: ["80:80", "443:443"]
    volumes:
      - nginx_proxy_vhost.d:/etc/nginx/vhost.d
      - nginx_proxy_html:/usr/share/nginx/html
      - ./proxy-default.conf:/etc/nginx/conf.d/my-proxy.default.conf:ro
      - ./le-cert:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    networks:
      - default
      - backend 

  letsencrypt-nginx-proxy-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    restart: always
    environment:
      DEFAULT_EMAIL: "it@simulalab.org"
    volumes:
      - nginx_proxy_vhost.d:/etc/nginx/vhost.d
      - nginx_proxy_html:/usr/share/nginx/html
      - ./le-cert:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh

volumes:
  nginx_proxy_vhost.d:
  nginx_proxy_html:
  acme:

networks:
  backend:
